server:
  port: 8080


logging:
  file:
    name: logs/se452.log
    # maximum log file size in bytes, before rotation
    max-size: 10MB
    # number of backup files to keep
    max-history: 7
    rolling:
      enabled: true
      file-name-pattern: se452-%d{yyyy-MM-dd}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: ERROR
    edu.se352.group1.se352group1: DEBUG


spring:
  datasource:
    url: "jdbc:h2:mem:demo-db"
    driverClassName: "org.h2.Driver"
    username: test
    password: test
  h2:
    console.enabled: true

  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true