app:
  doc:
    version: 2024-Spring
    title: SE352-452 Hotel Reservation Project Demo
    description: This is a documentation for SE352-452 Concepts a library for OpenAPI with spring boot.
    terms-of-service: http://swagger.io/terms/
    license:  Apache 2.0
    url: http://springdoc.org

spring:
  profiles:
    active: dev